# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#

name: Pirate Chain (ARRR)
title: Pirate Chain | Money Made Private
email: marketing@pirate.black
keywords: cryptocurrency, privacy, pirate chain, arrr, fungible
description: Pirate Chain is a privacy-focused cryptocurrency that uses zk-SNARKs technology to enable anonymous transactions. It is designed to be resistant to surveillance and censorship, and aims to provide a secure and private platform for financial transactions. The project has a strong emphasis on privacy and decentralization.
locale: en_US
lang: en
baseurl: "/pirate.black/"
url: "" # https://pirate.black
img: assets/img/
default_thumbnail: meta/pirate.jpeg
twitter_username: PirateChain
github_username:  PirateNetwork
